// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBIrMmpqPP0EN3PDjktAmMN9qTy8VZO-8',
    appId: '1:384993735321:android:f1c961b4f7af7898d47e08',
    messagingSenderId: '384993735321',
    projectId: 'novalith-c49fb',
    databaseURL: 'https://novalith-c49fb-default-rtdb.firebaseio.com',
    storageBucket: 'novalith-c49fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZJrhOKs5CHb4HDBTRhMbBpdHOtJ8Lic',
    appId: '1:384993735321:ios:9f782beb4051191ad47e08',
    messagingSenderId: '384993735321',
    projectId: 'novalith-c49fb',
    databaseURL: 'https://novalith-c49fb-default-rtdb.firebaseio.com',
    storageBucket: 'novalith-c49fb.firebasestorage.app',
    iosBundleId: 'com.aries.novalith',
  );
}
