name: Flutter CI

on:
  push:
    branches:
      - dev-ci/cd
  pull_request:
    branches:
      - dev-ci/cd

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0

      - name: Install Dependencies
        run: flutter pub get
        working-directory: Software/novalith
